### ISSUE TITLE
rel-me URLs with paths considered invalid

### ISSUE THREAD

**Issue by evanminto** [aaronpk/IndieAuth-Token-Endpoint#4]
When the "me" URL has a path in it (http://example.com/evan vs. http://example.com), it's considered an invalid URL, causing sign-in to fail. It seems like https://github.com/aaronpk/IndieAuth-Token-Endpoint/blob/98e637718d1821a451a46dcbcb0b56c69f187fe9/lib/helpers.php#L39 is causing it.

Ran into this while testing my Micropub implementation. Your clients (Quill, OwnYourGram) throw an error, but Woodwind, for example, does not — not sure if this is just because Woodwind ignores the error. I may be missing something, but it seems like IndieAuth **should** be able to accept URLs with paths.

If there's a reason for this that I'm not aware of, I'd appreciate the education (I'm pretty new to IndieWeb/Social Web development). Otherwise, it seems like a bug to me.

Example error from OwnYourGram:
![screen shot 2017-01-07 at 3 09 20 pm](https://cloud.githubusercontent.com/assets/616660/21745967/cb3b24e0-d4eb-11e6-9fed-59ab73d78e87.png)

**Comment by aaronpk** [comment]
Fixed in af25636776d609f76e9a3f433d83696df50f7b72. Sorry I didn't see your PR earlier!
